# GitHub Sponsors integration for AGENT-11

# Buy Me a Coffee (official support as of March 2024)
custom: https://buymeacoffee.com/jamiewatters

# GitHub Sponsors (if/when enabled in the future)
# github: [jamiewatters]
