blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/TheWayWithin/agent-11/blob/main/DOCUMENTATION-INDEX.md
    about: Complete documentation and guides
  - name: 🚀 Quick Start
    url: https://github.com/TheWayWithin/agent-11/blob/main/QUICK-START.md
    about: Deploy AGENT-11 in under 5 minutes
  - name: 🔧 Troubleshooting
    url: https://github.com/TheWayWithin/agent-11/blob/main/TROUBLESHOOTING.md
    about: Fix common installation and usage issues
  - name: 💬 Community Discussions
    url: https://github.com/TheWayWithin/agent-11/discussions
    about: Ask questions and share experiences with the community