title: "Built something awesome with AGENT-11!"
body: |
  **What I built:**
  <!-- Brief description of your project -->
  
  **Which agents I used:**
  <!-- Core Squad / Full Squad / Custom selection -->
  
  **Key results:**
  <!-- Time saved, features built, business outcomes, etc. -->
  
  **My favorite AGENT-11 workflow:**
  <!-- How do you use the agents together? Any tips? -->
  
  **Screenshots/demos (optional):**
  <!-- Show off your work! -->
  
  **Advice for other founders:**
  <!-- What would you tell someone just starting with AGENT-11? -->
  
  ---
  
  **Deployment stats:**
  - Installation time: 
  - Squad type: 
  - Project type: 
  - Development time: 
  
  🎉 Congrats on shipping! The community would love to hear about your experience.
labels: show-and-tell